### ISSUE TITLE
Problems sorting search results by dc.date.accessioned ascending - Dspace8

### ISSUE THREAD

**Issue by aroldorique** [DSpace/DSpace#10768]
Hi

I'm having trouble sorting the results of a search by the dc.date.accessioned metadata in ascending order. My discovery.xml is configured as follows.

```
<!--The sort filters for the discovery search-->
        <property name="searchSortConfiguration">
            <bean class="org.dspace.discovery.configuration.DiscoverySortConfiguration">
                <property name="sortFields">
                    <list>
                          <ref bean="sortDateAccessioned"/>                        
                          <ref bean="sortDateAccessionedAsc"/>
                          <ref bean="sortTitle"/>
                    </list>
                </property>
            </bean>
        </property>

<bean id="sortDateAccessionedAsc" class="org.dspace.discovery.configuration.DiscoverySortFieldConfiguration">
        <property name="metadataField" value="dc.date.accessioned"/>
        <property name="type" value="date"/>
        **<property name="defaultSortOrder" value="asc"/>**
    </bean>
```

Note that the first results are collection records, which don't even have the dc.date.accessioned metadata. What could be happening?

Link: https://biblioteca.mpf.mp.br/repositorio/search?spc.page=1&spc.sf=dc.date.accessioned&spc.sd=ASC

![Image](https://github.com/user-attachments/assets/597e4696-5eca-4bc5-8178-ec618720b5b3)

Aroldo

**Comment by jesielviana** [comment]
Hi @aroldorique, the link not working.

**Comment by aroldorique** [comment]
> Hi [@aroldorique](https://github.com/aroldorique), the link not working.

Please try again.

**Comment by jensvannerum** [comment]
This is default and normal behavior in Solr, when sorting ascending null values will be first in the list.

You can work around this with a multi valued sort that also sorts on `exists(dc.date.accessioned_dt) desc`

For example your issue is present with:
```
http://localhost:28993/solr/search/select?q=*:*&sort=dc.date.accessioned_dt%20asc
```

But fixed with:

```
http://localhost:28993/solr/search/selectq=*:*&sort=exists(dc.date.accessioned_dt)%20desc,dc.date.accessioned_dt%20asc
```

~~I will introduce a property on the sortFilter class to make this configurable from within dspace~~

Actually you can simply modify your search core schema.xml to include `sortMissingLast="true"` on either the `date` fieldType or only on this specific field. Whether this should be default DSpace behavior is another discussion I guess

**Comment by aroldorique** [comment]
> This is default and normal behavior in Solr, when sorting ascending null values will be first in the list.
> 
> You can work around this with a multi valued sort that also sorts on `exists(dc.date.accessioned_dt) desc`
> 
> For example your issue is present with:
> 
> ```
> http://localhost:28993/solr/search/select?q=*:*&sort=dc.date.accessioned_dt%20asc
> ```
> 
> But fixed with:
> 
> ```
> http://localhost:28993/solr/search/selectq=*:*&sort=exists(dc.date.accessioned_dt)%20desc,dc.date.accessioned_dt%20asc
> ```
> 
> ~I will introduce a property on the sortFilter class to make this configurable from within dspace~
> 
> Actually you can simply modify your search core schema.xml to include `sortMissingLast="true"` on either the `date` fieldType or only on this specific field. Whether this should be default DSpace behavior is another discussion I guess

Hello, thanks for the reply.

My /solr/statistics/conf/schema.xml file already looks like this, but the ascending ordering issue persists:

`<fieldType name="date" class="solr.DatePointField" sortMissingLast="true" omitNorms="true" docValues="true"/>`

**Comment by jensvannerum** [comment]
@aroldorique

> My /solr/statistics/conf/schema.xml file already looks like this

That would be your _statistics_ core while this configuration should be applied to the _search_ core

**Comment by aroldorique** [comment]
I also added `sortMissingLast="true"` to the date fieldType in /dspace8/solr/search/conf/schema.xml

<img width="980" height="411" alt="Image" src="https://github.com/user-attachments/assets/c04d77f9-7409-4721-9d94-5c7310ab0cb9" />


But nothing has changed yet. The first results sorted ascending are still collection or community names.

**Comment by jensvannerum** [comment]
Have you restarted your solr instance after this change ?

I've verified this works locally once more, to double check you could also look in the Solr UI at `http://localhost:{port}/solr/#/search/schema?field=dc.date.accessioned_dt` (or whatever field is being used but it should be this one by default) and make sure you can see that checkmark at "sort missing last"

<img width="709" height="190" alt="Image" src="https://github.com/user-attachments/assets/8a358c36-c21b-4e54-92fe-5ba40ac92f7e" />

**Comment by aroldorique** [comment]
After I restarted Solr. It worked!!! Thank you very much!!!

**Comment by aroldorique** [comment]
And what about sorting by title in ascending order, as in the image below? What should I do to prevent records from collections and communities from appearing in the results?

Example: https://demo.dspace.org/search?spc.page=1&spc.sf=dc.title&spc.sd=ASC

<img width="1458" height="992" alt="Image" src="https://github.com/user-attachments/assets/65a88f73-9300-483d-9380-07466926cf0c" />

**Comment by aroldorique** [comment]
The solution I found was to modify `defaultFilterQueries`, replacing this line:
`<value>(search.resourcetype:Item AND latestVersion:true) OR search.resourcetype:Collection OR search.resourcetype:Community</value>`
With this one:
`<value>search.resourcetype:Item AND latestVersion:true</value>`

Aroldo
