### ISSUE TITLE
Search endpoint has incorrect "self link"

### ISSUE THREAD

**Issue by MW3000** [DSpace/DSpace#8576]
**Describe the bug**
When using the UI, there appears a ensureSelfLink warning in the browser console when searching. Open your browser's console for warning messages and issue a search request: You will find this warning in your console:

> The response for 'https://api7.dspace.org/server/api/discover/search?configuration=default' has the self link 'https://api7.dspace.org/server/api/discover/search'. These don't match. This could mean there's an issue with the REST endpoint

I experience this with our own installation of DSpace and it can be observed on https://demo7.dspace.org

There has been a similar issue a while ago opened and closed on the backend project: https://github.com/DSpace/DSpace/issues/3138

**To Reproduce**
1. Go to https://demo7.dspace.org
2. Enter a search term and click search
3. Open your browser's console and read: "The response for 'https://api7.dspace.org/server/api/discover/search?configuration=default' has the self link 'https://api7.dspace.org/server/api/discover/search'. These don't match. This could mean there's an issue with the REST endpoint"

**Comment by buithaihai** [comment]
I would like to sign up for this issue along with issue #8577 as my first contribution to DSpace, on behalf of DLCorp. I am currently finishing setting up a development environment and hopefully, are able to create a fix for both issues this week.

**Comment by tdonohue** [comment]
@buithaihai : Thank you for volunteering!  Please feel free to send us a Pull Request for one or both fixes when you have the chance.  See our contribution guide for more information: https://github.com/DSpace/DSpace/blob/main/CONTRIBUTING.md

**Comment by almereyda** [comment]
Is this resolved in newer versions?

**Comment by lgeggleston** [comment]
@almereyda I do not observe this bug currently via demo.dspace.org or sandbox.dspace.org, so it appears to be resolved in the latest versions.  Closing now, but please let me know if someone is still able to reproduce this error and we can reopen it.

**Comment by tinsch** [comment]
The issue seems to be resolved on the search page itself, but item pages do still seem to have a similar issue.

When I open https://sandbox.dspace.org/items/bb3eb3d2-9796-4a6b-b08e-af914e2438a9 coming from here https://sandbox.dspace.org/collections/82e086f1-a26b-4d39-b7ca-78abc507f539/search I see 7 warnings of the kind mentioned in this ticket.

**Comment by lgeggleston** [comment]
@tinsch thank you for checking this! Looks like those same (generic) warnings on the item pages are covered by this adjacent issue: https://github.com/DSpace/DSpace/issues/8577, so I'll just leave this one closed but comment/bump the other since it's been re-observed.

**Comment by lgeggleston** [comment]
Reopening this as it was observed again; PR up with additional context and ready for review: https://github.com/DSpace/DSpace/pull/12984

I mistakenly closed this earlier - While it is no longer occurring on the main Search results page, the `/discover/search` endpoint is still throwing this error on any page that runs a scoped search with url parameters - for example: https://demo.dspace.org/entities/person/simmons-cameron
